### ISSUE TITLE
signup page

### ISSUE THREAD

**Issue by jywarren** [publiclab/wherewebreathe#7]
This is where we might ask about VIN #, and be very clear about pseudonym and privacy issues (i.e. your answers will be public, or at least show a "privacy switch"?)

See https://github.com/publiclab/wherewebreathe/issues/4#issuecomment-42527914 for VIN discussion.

**Task list:**
- [x] figure out over-18 question
- [x] use "manufactured housing" as vocab
- [x] HUD & VIN or HUD || VIN?
- [x] "how to find HUD & VIN" blurb & photos (modal?)
- [x] use email as login mechanism, not username. 
- [ ] indicate which parts of a VIN we may use? or none, if we'll ask it as part of the survey
- [ ] username generator: use animal names? or some ungendered naming convention: "BlueGiraffe34"
